### PR TITLE
Refactor to use ViewModel instead of native Blaze

### PR DESCRIPTION
**Pull request by dalgard**
Right, so it didn't actually reduce the amount of code at all :D

I do feel, however, that this method has some merit in regard to keeping things declarative, and also because the state of the forms is now preserved across hot code pushes, as well as, as a novelty add-on, across routes.

Anyway, if you wanted to use a viewmodel approach in the future, I would think it a wise decision for a number of reasons besides the ones mentioned.

Cheers :)

### CODE REVIEW

**Comment by frabrunelle** [comment]
Thank you so much!

I really like the ViewModel pattern and I will try to use it as much as I can :smiley: 

> because the state of the forms is now preserved across hot code pushes

That's a killer feature! :grinning: 

> as well as, as a novelty add-on, across routes.

I like this feature a lot too! Very useful.

I truly appreciate that you are developing this package! I've felt for a while that this was a big missing piece in Blaze. I looked at `manuel:viewmodel` a few times and tried to integrate it, but I wasn't fully satisfied. I really like your approach! And you released it at the perfect timing for me to use it in my app :smile: 

I would like to offer you [this bounty](https://www.bountysource.com/issues/26342780-update-register-js-to-use-the-viewmodel-pattern) as a gift. Feel free to claim it if you are comfortable with accepting it :smile:

**Comment by dalgard** [comment]
That's a really nice gesture – thanks. I think I'll leave it, though, since it's already quite helpful to me, that you've supplied me with your use case.

Bitcoin is an interesting subject. Lots of luck with the project.

**Comment by frabrunelle** [comment]
> I think I'll leave it, though, since it's already quite helpful to me, that you've supplied me with your use case.

Fair enough :smile: 

> Bitcoin is an interesting subject. Lots of luck with the project.

Thank you :smile: I think Bitcoin is cool but there is no words to describe how excited I am by the SAFE Network (which is being developed by [MaidSafe](http://maidsafe.net)). It's not quite [launched](http://maidsafe.net/roadmap) yet (even though it's been in development for almost 10 years now :stuck_out_tongue: ), but hopefully by the end of the year!

But since I work and live at the Bitcoin Embassy, I often help my friends with their Bitcoin projects. So my current project is to build an online equivalent of their [Satoshi Counter](http://satoshicounter.com) business, which is a physical counter located at the Bitcoin Embassy where people can buy and sell bitcoins. There is another developer working with me and we are trying to launch an MVP version within 6 weeks :smiley:

**Comment by dalgard** [comment]
I hope you do :)

**Pull request merged**
